STATUS_IN_STOCK = 'IN_STOCK'
STATUS_SOLD_OUT = 'SOLD_OUT'
STATUS_COMING_SOON = 'COMING_SOON'

ALLOWED_SIZE_STATUSES = (
    STATUS_IN_STOCK,
    STATUS_SOLD_OUT,
    STATUS_COMING_SOON,
)

ALLOWED_PRODUCT_STATUSES = (
    STATUS_IN_STOCK,
    STATUS_SOLD_OUT,
    STATUS_COMING_SOON,
)
